### PR TITLE
Use lockfile to coordinate access to binary executable

### LINKED ISSUE #91: KPL Binary installation uses a Shared Lock
The KPL binary is vulnerable to a race condition that yields a zero-byte binary file being installed. The sequence is:

1. Process-1 determines that the binary does not exist and creates a new `FileOutputStream`, which will create a file-descriptor on the filesystem ([link](https://github.com/awslabs/amazon-kinesis-producer/blob/master/java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java#L827))
2. Process-2 determines that the file exists and creates a `FileInputStream` and shared lock: ([link](https://github.com/awslabs/amazon-kinesis-producer/blob/master/java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java#L814-L815))
3. Process-1 attempts to create an exclusive lock but cannot because Process-2 has a shared-lock that prevents the creation of exclusive locks: ([link](https://github.com/awslabs/amazon-kinesis-producer/blob/master/java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java#L828))
4. Process-2 verifies the contents of the binary and throws a `SecurityException` because the contents do not match the expected value: ([link](https://github.com/awslabs/amazon-kinesis-producer/blob/master/java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java#L816-L824))

This can be avoided by using a dedicated lock-file separate from the binary file being written.

This issue is related to #55

### PR DESCRIPTION
**Pull request by skidder**
Fixes #91 

The approach of creating & locking the executable file in a non-atomic way can lead to a race condition. Instead, we should use a dedicated lockfile to coordinate access to the executable.

### CODE REVIEW

**Comment by jghoman** [comment]
We're running into this as well.  Can someone from AWS please review and commit?

**Comment by pfifer** [comment]
Please confirm that we can use, modify, copy, and redistribute this contribution. 

Thanks.

**Comment by skidder** [comment]
Yes, you can use, modify, copy, and redistribute this contribution.

**Comment by skidder** [comment]
@pfifer this PR is good to go, sorry for the lag in granting you permission to use it.

**Pull request merged**
