### PR TITLE
Make KPL consumers more testable

### PR DESCRIPTION
**Pull request by JeffAtDeere**
Introduced interface on KinesisProducer for testability/mockability.
Introduced UserRecord object and KinesisProducer.addUserRecord(UserRecord) method.

@pfifer 

This commit was done with 100% backwards compatibility in mind.

### CODE REVIEW

**Comment by pfifer** [comment]
Is the testing goal for increase unit testing in the KPL, or for your own unit testing?

My feeling is that if it's for the KPL the private constructors should be package private. If it's for your own testing public makes more sense.

**Comment by JeffAtDeere** [comment]
Excellent question. This is for testing of my things that use KPL. The private constructors mean I can't make instances nor can I mock over them.

**Comment by JeffAtDeere** [comment]
Similar reasoning for the interface on `KinesisProducer` -- `KinesisProducer`s no arg constructor tries (via another constructor) to `extractBinaries()` which fails on windows, meaning I can't mock over or make new instances of `KinesisProducer` on a windows machine. With an interface, even on Linux (where binaries are available) the mock won't start the child daemon.

**Comment by JeffAtDeere** [comment]
@pfifer does that make sense? If so, can you merge this or let me know if any changes are required? Thank you.

**Comment by pfifer** [comment]
Yes it makes sense.  I'm currently in the process of planning, and preparing a release.  I will have an update hopefully later this week.

**Comment by pfifer** [comment]
Please confirm that we can use, modify, copy, and redistribute this contribution. Thanks.

**Comment by JeffAtDeere** [comment]
I checked and can confirm.

**Pull request merged**
