### PR TITLE
Adding release notes for 0.14.2 release.

### PR DESCRIPTION
**Pull request by yatins47**
*Issue #, if available:*

*Description of changes:* Adding release notes for 0.14.2 release.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by blacktooth — APPROVED** [review]

**Review by ashwing — COMMENTED** [review]
lgtm

**Review by ashwing — COMMENTED** [review]
Need to update the versions in POM

**Review by ashwing — COMMENTED** [review]
lgtm

**Review by ashwing — APPROVED** [review]
lgtm

**Pull request merged**
